baseURL = "https://liquid-system.github.io"
languageCode = "ja-JP"
defaultContentLanguage = "en"
hasCJKLanguage = true
Paginate = 5

title = "時祷書"
theme = "kiss"
canonifyurls = true
showToc = true
copyright = "&copy;2022 Liquid-system | <a href=\"https://github.com/Liquid-system\">github</a> | <a href=\"https://misskey.io/@Liquid_system\">misskey.io</a>"
