baseURL = "https://liquid-system.github.io"
contentDir = "content/post"
title = "時祷書"
theme = "kiss"
languageCode = "ja-JP"
defaultContentLanguage = "en"
hasCJKLanguage = true
Paginate = 5
canonifyurls = true
showToc = true
codeCopy = true
customCSS = ["css/custom.css"]
copyright = "&copy;2022 Liquid-system | <a href=\"https://github.com/Liquid-system\">github</a> | <a href=\"https://misskey.io/@Liquid_system\">misskey.io</a>"
[taxonomies]
tag ="tags"

[markup.goldmark.renderer]
hardWraps = true
unsafe = true

[params.info]
homeTitle = "時祷書"
dateFormat = "01/02"

[params.assets]
customCSS = ["css/custom.css"]
googleFonts = ["Noto Sans JP"]
